import type { Achievement } from '@/types';

// 成就列表
export const ACHIEVEMENTS: Achievement[] = [
  // ========== 连击里程碑 ==========
  {
    id: 'streak-3',
    type: 'streak',
    title: '初学者',
    description: '连续学习 3 天',
    icon: 'Sparkles',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 'streak-7',
    type: 'streak',
    title: '坚持一周',
    description: '连续学习 7 天',
    icon: 'Flame',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'streak-21',
    type: 'streak',
    title: '习惯养成',
    description: '连续学习 21 天',
    icon: 'Trophy',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'streak-50',
    type: 'streak',
    title: '学习达人',
    description: '连续学习 50 天',
    icon: 'Zap',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'streak-100',
    type: 'streak',
    title: '博学大家',
    description: '连续学习 100 天',
    icon: 'Crown',
    color: '#FFD700',
    unlocked: false,
  },
  {
    id: 'streak-150',
    type: 'streak',
    title: '持之以恒',
    description: '连续学习 150 天',
    icon: 'Hourglass',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'streak-200',
    type: 'streak',
    title: '学无止境',
    description: '连续学习 200 天',
    icon: 'Infinity',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'streak-365',
    type: 'streak',
    title: '年度学霸',
    description: '连续学习 365 天',
    icon: 'Calendar',
    color: '#FFD700',
    unlocked: false,
  },

  // ========== 首次成就 ==========
  {
    id: 'first-lesson',
    type: 'lesson',
    title: '迈出第一步',
    description: '完成第一节课',
    icon: 'BookOpen',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'first-chapter',
    type: 'chapter',
    title: '章节通关',
    description: '通过第一个章节测验',
    icon: 'Award',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'first-perfect',
    type: 'accuracy',
    title: '一击即中',
    description: '一次性答对某章节/课程所有题目',
    icon: 'Target',
    color: '#7AAEC0',
    unlocked: false,
  },

  // ========== 学科通关 ==========
  {
    id: 'first-subject',
    type: 'subject',
    title: '学科入门',
    description: '通过任意一门学科的通关测验（≥80%）',
    icon: 'GraduationCap',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'dual-master',
    type: 'subject',
    title: '双学科精通',
    description: '通过两门学科的通关测验',
    icon: 'Star',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'triple-master',
    type: 'subject',
    title: '三科达人',
    description: '通过三门学科的通关测验',
    icon: 'Gem',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'polymath',
    type: 'subject',
    title: '博学者',
    description: '通过四门及以上学科的通关测验',
    icon: 'Sparkles',
    color: '#FFD700',
    unlocked: false,
  },

  // ========== 探索成就 ==========
  {
    id: 'all-first-chapters',
    type: 'exploration',
    title: '广泛探索',
    description: '完成所有学科的第一章',
    icon: 'Compass',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 'first-knowledge-graph',
    type: 'exploration',
    title: '图谱探索者',
    description: '解锁第1个知识概念',
    icon: 'Network',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'knowledge-concept-10',
    type: 'exploration',
    title: '概念收集',
    description: '解锁10个知识概念',
    icon: 'BookOpen',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 'knowledge-concept-30',
    type: 'exploration',
    title: '概念猎手',
    description: '解锁30个知识概念',
    icon: 'Search',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'knowledge-fallacy-5',
    type: 'exploration',
    title: '谬误识别',
    description: '解锁5个逻辑谬误',
    icon: 'AlertTriangle',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'knowledge-effect-5',
    type: 'exploration',
    title: '效应洞察',
    description: '解锁5个心理/管理效应',
    icon: 'Lightbulb',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'knowledge-law-5',
    type: 'exploration',
    title: '定律掌握',
    description: '解锁5个定律/法则',
    icon: 'Scale',
    color: '#7BB661',
    unlocked: false,
  },

  // ========== 掌握度成就 ==========
  {
    id: 'master-10',
    type: 'mastery',
    title: '知识积累',
    description: '完成10节课',
    icon: 'Library',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'master-25',
    type: 'mastery',
    title: '知识渊博',
    description: '完成25节课',
    icon: 'BookMarked',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'master-50',
    type: 'mastery',
    title: '学富五车',
    description: '完成50节课',
    icon: 'GraduationCap',
    color: '#D4A574',
    unlocked: false,
  },

  // ========== 准确率成就 ==========
  {
    id: 'hot-streak-5',
    type: 'accuracy',
    title: '手感火热',
    description: '连续答对5道题',
    icon: 'Flame',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'perfect-chapter',
    type: 'accuracy',
    title: '完美章节',
    description: '章节测验满分（100%）',
    icon: 'CheckCircle',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'perfect-final',
    type: 'accuracy',
    title: '完美通关',
    description: '通关测验满分（100%）',
    icon: 'Award',
    color: '#FFD700',
    unlocked: false,
  },
  {
    id: 'hot-streak-10',
    type: 'accuracy',
    title: '火力全开',
    description: '连续答对10道题',
    icon: 'Flame',
    color: '#FF6B35',
    unlocked: false,
  },
  {
    id: 'hot-streak-20',
    type: 'accuracy',
    title: '无可阻挡',
    description: '连续答对20道题',
    icon: 'Zap',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'accuracy-80',
    type: 'accuracy',
    title: '精准射手',
    description: '累计答题准确率达到80%',
    icon: 'Target',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'accuracy-90',
    type: 'accuracy',
    title: '百发百中',
    description: '累计答题准确率达到90%',
    icon: 'Bullseye',
    color: '#7AAEC0',
    unlocked: false,
  },

  // ========== 阅读时长成就 ==========
  {
    id: 'read-100',
    type: 'exploration',
    title: '书海初航',
    description: '累计阅读时长达到100分钟',
    icon: 'Clock',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 'read-500',
    type: 'exploration',
    title: '孜孜不倦',
    description: '累计阅读时长达到500分钟',
    icon: 'BookOpen',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'read-1000',
    type: 'exploration',
    title: '博览群书',
    description: '累计阅读时长达到1000分钟',
    icon: 'Library',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'read-5000',
    type: 'exploration',
    title: '学识渊博',
    description: '累计阅读时长达到5000分钟',
    icon: 'GraduationCap',
    color: '#FFD700',
    unlocked: false,
  },

  // ========== 复习成就 ==========
  {
    id: 'review-first',
    type: 'mastery',
    title: '温故知新',
    description: '完成首次复习',
    icon: 'RefreshCw',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'review-5',
    type: 'mastery',
    title: '复习达人',
    description: '累计复习5次',
    icon: 'RotateCcw',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'review-20',
    type: 'mastery',
    title: '熟能生巧',
    description: '累计复习20次',
    icon: 'Repeat',
    color: '#D4A574',
    unlocked: false,
  },

  // ========== 掌握度成就（扩展） ==========
  {
    id: 'master-100',
    type: 'mastery',
    title: '博闻强识',
    description: '完成100节课',
    icon: 'BookMarked',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 'master-200',
    type: 'mastery',
    title: '无所不知',
    description: '完成200节课',
    icon: 'Globe',
    color: '#FFD700',
    unlocked: false,
  },

  // ========== 知识图谱成就 ==========
  {
    id: 'graph-full-explore',
    type: 'exploration',
    title: '图谱探险家',
    description: '浏览完所有学科的知识图谱',
    icon: 'Network',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'graph-connect-10',
    type: 'exploration',
    title: '知识连接者',
    description: '查看过10个知识节点的详细内容',
    icon: 'Link',
    color: '#7BB661',
    unlocked: false,
  },

  // ========== 错题本成就 ==========
  {
    id: 'wrong-zero',
    type: 'accuracy',
    title: '零错题',
    description: '错题本清空',
    icon: 'CheckCircle',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'wrong-review-5',
    type: 'accuracy',
    title: '查漏补缺',
    description: '复习并掌握5道错题',
    icon: 'Edit3',
    color: '#9B7BB8',
    unlocked: false,
  },

  // ========== 学科专属成就 ==========
  // 经济学
  {
    id: 'e-first-chapter',
    type: 'subject-specific',
    title: '供需入门',
    description: '完成经济学第一章',
    icon: 'TrendingUp',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'e-master-5',
    type: 'subject-specific',
    title: '市场洞察',
    description: '完成经济学5节课',
    icon: 'BarChart',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'e-chapter-pass',
    type: 'subject-specific',
    title: '经济思维',
    description: '通过经济学章节测验',
    icon: 'Brain',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'e-subject-pass',
    type: 'subject-specific',
    title: '经济达人',
    description: '通过经济学通关测验',
    icon: 'Landmark',
    color: '#7BB661',
    unlocked: false,
  },
  {
    id: 'e-mastery-80',
    type: 'subject-specific',
    title: '供需大师',
    description: '经济学掌握度达到80%',
    icon: 'Target',
    color: '#7BB661',
    unlocked: false,
  },
  // 社会学
  {
    id: 's-first-chapter',
    type: 'subject-specific',
    title: '社会观察',
    description: '完成社会学第一章',
    icon: 'Users',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 's-master-5',
    type: 'subject-specific',
    title: '社会洞察',
    description: '完成社会学5节课',
    icon: 'Eye',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 's-chapter-pass',
    type: 'subject-specific',
    title: '社会思考',
    description: '通过社会学章节测验',
    icon: 'MessageCircle',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 's-subject-pass',
    type: 'subject-specific',
    title: '社会达人',
    description: '通过社会学通关测验',
    icon: 'Globe',
    color: '#7AAEC0',
    unlocked: false,
  },
  {
    id: 's-mastery-80',
    type: 'subject-specific',
    title: '社会学家',
    description: '社会学掌握度达到80%',
    icon: 'Target',
    color: '#7AAEC0',
    unlocked: false,
  },
  // 逻辑学
  {
    id: 'l-first-chapter',
    type: 'subject-specific',
    title: '逻辑入门',
    description: '完成逻辑学第一章',
    icon: 'Puzzle',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'l-master-5',
    type: 'subject-specific',
    title: '推理高手',
    description: '完成逻辑学5节课',
    icon: 'Lightbulb',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'l-chapter-pass',
    type: 'subject-specific',
    title: '逻辑思维',
    description: '通过逻辑学章节测验',
    icon: 'Brain',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'l-subject-pass',
    type: 'subject-specific',
    title: '逻辑达人',
    description: '通过逻辑学通关测验',
    icon: 'Cpu',
    color: '#D4A574',
    unlocked: false,
  },
  {
    id: 'l-mastery-80',
    type: 'subject-specific',
    title: '逻辑大师',
    description: '逻辑学掌握度达到80%',
    icon: 'Target',
    color: '#D4A574',
    unlocked: false,
  },
  // 心理学
  {
    id: 'p-first-chapter',
    type: 'subject-specific',
    title: '心理探索',
    description: '完成心理学第一章',
    icon: 'Search',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'p-master-5',
    type: 'subject-specific',
    title: '心理洞察',
    description: '完成心理学5节课',
    icon: 'Eye',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'p-chapter-pass',
    type: 'subject-specific',
    title: '心理思考',
    description: '通过心理学章节测验',
    icon: 'Brain',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'p-subject-pass',
    type: 'subject-specific',
    title: '心理达人',
    description: '通过心理学通关测验',
    icon: 'Heart',
    color: '#D08068',
    unlocked: false,
  },
  {
    id: 'p-mastery-80',
    type: 'subject-specific',
    title: '心理学家',
    description: '心理学掌握度达到80%',
    icon: 'Target',
    color: '#D08068',
    unlocked: false,
  },
  // 管理学
  {
    id: 'm-first-chapter',
    type: 'subject-specific',
    title: '管理入门',
    description: '完成管理学第一章',
    icon: 'Briefcase',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'm-master-5',
    type: 'subject-specific',
    title: '管理高手',
    description: '完成管理学5节课',
    icon: 'TrendingUp',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'm-chapter-pass',
    type: 'subject-specific',
    title: '管理思维',
    description: '通过管理学章节测验',
    icon: 'Brain',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'm-subject-pass',
    type: 'subject-specific',
    title: '管理达人',
    description: '通过管理学通关测验',
    icon: 'Award',
    color: '#9B7BB8',
    unlocked: false,
  },
  {
    id: 'm-mastery-80',
    type: 'subject-specific',
    title: '管理大师',
    description: '管理学掌握度达到80%',
    icon: 'Target',
    color: '#9B7BB8',
    unlocked: false,
  },
];

// 连击里程碑阈值
export const STREAK_MILESTONES = [3, 7, 21, 50, 100, 150, 200, 365];
